import type { ParametrosGlobais } from "./types";

export const DEFAULT_PARAMETROS_GLOBAIS: ParametrosGlobais = {
  k: {
    mg_dm3_para_kg_ha: 390,
    fator_k_para_k2o: 1.31,
    fator_k_para_k2o_alvo: 1.2046,
    alvo_mg_dm3: 0.85,
    participacao_ctc_ideal: 0.03,
    participacao_ctc_maxima: 0.05,
    correcao_k2o_kg_ha: 100,
    aproveitamento_correcao: 0.6,
    limite_tecnico_sulco_kg_ha: 120,
  },
  calcio: {
    alvo_cmol_dm3: 7.5,
    garantia_ca_calcario: 0.3,
    garantia_mg_calcario: 0.2,
    prnt: 1,
    fator_cmol_para_kg_ha: 500,
    relacao_ca_mg_limite_calcitico: 1.5,
    relacao_ca_mg_limite_dolomitico: 3,
  },
  fosforo: {
    alvo_mg_dm3: 4.5,
    fator_objetivo: 4.5,
    fator_disponibilidade_solo: 0,
    coeficiente_prem_a: 0.324731,
    coeficiente_prem_b: 0.00160568,
    coeficiente_prem_c: 4.62,
    teor_argila_alto: 60,
    teor_argila_medio: 35,
    teor_argila_baixo: 15,
    retencao_argila_alta: 12,
    retencao_argila_media: 25,
    retencao_argila_baixa: 30,
    retencao_argila_muito_baixa: 25,
    constante_equilibrio_kg_ha: 36,
    concentracao_produto: 0.3,
  },
  magnesio: {
    alvo_cmol_dm3: 2.5,
  },
  materia_organica: {
    ideal_min_percent: 3,
    ideal_max_percent: 5,
  },
  enxofre: {
    alvo_mg_dm3: 10,
    fator_mg_dm3_para_kg_ha: 15,
    fator_disponibilidade_solo: 0,
    concentracao_enxofre_elementar: 0.9,
  },
  producao: {
    cultura_padrao: "Soja",
    produtividade_padrao_bolsas_ha: 60,
    produtividade_alta_bolsas_ha: 75,
    k2o_por_bolsa: 1.3,
    fator_kcl: 1.6667,
    p2o5_por_bolsa: 1.2,
    so4_por_bolsa: 0.93,
  },
  micros: {
    concentracao_produto: 0.1,
    boro: {
      minimo_mg_dm3: 0.75,
      maximo_mg_dm3: 1,
      fator_mg_dm3_para_kg_ha: 2,
    },
    cobre: {
      minimo_mg_dm3: 1.5,
      maximo_mg_dm3: 6.5,
      fator_mg_dm3_para_kg_ha: 2,
    },
    ferro: {
      minimo_mg_dm3: 15,
      maximo_mg_dm3: 40,
      fator_mg_dm3_para_kg_ha: 2,
    },
    zinco: {
      minimo_mg_dm3: 4,
      maximo_mg_dm3: 12,
      fator_mg_dm3_para_kg_ha: 2.5,
    },
    manganes: {
      minimo_mg_dm3: 10,
      maximo_mg_dm3: 40,
      fator_mg_dm3_para_kg_ha: 2,
    },
  },
  fertilizante: {
    formula_nome: "30-10-6",
    dose_kg_ha: 200,
    percentual_p2o5: 30,
    percentual_k2o: 10,
    percentual_so4: 6,
    formulas_opcoes: [
      { id: "f-30-10-6", nome: "30-10-6", percentual_p2o5: 30, percentual_k2o: 10, percentual_so4: 6 },
      { id: "f-00-20-20", nome: "00-20-20", percentual_p2o5: 20, percentual_k2o: 20, percentual_so4: 0 },
      { id: "f-00-20-00", nome: "00-20-00", percentual_p2o5: 20, percentual_k2o: 0, percentual_so4: 0 },
      { id: "f-00-00-20", nome: "00-00-20", percentual_p2o5: 0, percentual_k2o: 20, percentual_so4: 0 },
      { id: "f-18-00-18", nome: "18-00-18", percentual_p2o5: 0, percentual_k2o: 18, percentual_so4: 18 },
    ],
  },
};
